#!/bin/bash

# Script to help track which files have been modified
echo "Files completed so far:"
echo "1. test_herk_device.cc - DONE"
echo "2. test_her2k_device.cc - DONE"
echo "3. test_symm_device.cc - DONE"
echo "4. test_syrk_device.cc - DONE"
echo ""
echo "Remaining files to process:"
echo "5. test_syr2k_device.cc"
echo "6. test_trmm_device.cc"
echo "7. test_trsm_device.cc"
echo "8. test_geadd_device.cc"
echo "9. test_tzadd_device.cc"
echo "10. test_rotg_device.cc"
echo "11. test_rotmg_device.cc"
echo "12. test_batch_gemm_device.cc"
echo "13. test_batch_hemm_device.cc"
echo "14. test_batch_her2k_device.cc"
echo "15. test_batch_herk_device.cc"
echo "16. test_batch_symm_device.cc"
echo "17. test_batch_syr2k_device.cc"
echo "18. test_batch_syrk_device.cc"
echo "19. test_batch_trmm_device.cc"
echo "20. test_batch_trsm_device.cc"
